config: 1

google:
  enabled: false
  client_secret: ""
  client_id: ""
  application_name: ""
  service_file: ""

twitter:
  enabled: false
  consumerKey: ""
  consumerSecret: ""
  accessToken: ""
  accessTokenSecret: ""
  owner: ""